### ISSUE TITLE
[Bug]: Can't close the search bar 

### ISSUE THREAD

**Issue by Anshu3301** [ChromeGaming/Community-Page#102]
### Give a brief about the bug :

=> After opening the search bar there's no option to close it!
![Screenshot (170)](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/134282893/7e0af805-cb00-4579-983a-bbce2dc565d4)

### What is the expected behavior? : 

=> There should be a  close button.

### Provide step by step information reproduce the bug:

=> I know it's a minor issue but still can you assign me this under GSSoC'24?   It would be my 1st open source contribution...

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by nilesh5566** [comment]
can you please assign this issue to me #102 ?

**Comment by Akashsingh7054** [comment]
i want to handle this issue can you please assign it to me.

**Comment by Durgesh4993** [comment]
@Anshu3301 margin & padding reduce

**Comment by Anshu3301** [comment]
I'll get it done...!
