### ISSUE TITLE
[Bug]: Request for Search Box Color Update for Improved Visibility

### ISSUE THREAD

**Issue by kvdevlopment** [ChromeGaming/Community-Page#105]
### Give a brief about the bug ✍️

**Description**
The current color of the search box on the website is too dark, making it difficult to view, particularly in dark mode. This affects the user experience as it hinders the ability to locate and utilize the search functionality effectively.

To enhance usability, I suggest updating the search box color to white or a lighter shade that provides better visibility, ensuring that users can easily identify and interact with the search feature regardless of the mode they are using.

### What is the expected behavior? 🤔

The expected behavior is that the search box color should be updated to a lighter shade, such as white, to ensure better visibility for users. This change will enhance the usability of the website, allowing users to easily locate and utilize the search functionality, regardless of the mode they are using (dark or normal).

### Provide step by step information reproduce the bug 📄

Navigate to the website: Go to the website where the search box with the dark color is located.

Toggle dark mode: If the website has a dark mode feature, enable it to observe the search box's visibility in a dark environment.

Locate the search box: Identify the search box on the website interface.

Observe visibility: Note the visibility of the search box against the background color, especially in dark mode. Determine if the dark color makes it difficult to see the search box clearly.

Compare with light mode: If possible, switch back to light mode (if applicable) and observe if the search box visibility improves with a lighter background.

Check for user feedback: Look for any existing user feedback or complaints regarding the search box visibility issue in dark mode. This could provide additional context and insights into the problem.

Inspect CSS styles: Use browser developer tools to inspect the CSS styles applied to the search box. Identify the color properties affecting its appearance.

Propose color change: Based on the observations and user feedback, propose a color change for the search box to improve visibility. Suggest updating the CSS styles to use a lighter color, such as white or a contrasting shade.

Test the proposed solution: If possible, test the suggested color change locally or on a staging environment to ensure that it effectively addresses the visibility issue without introducing any new problems.

Submit the solution: Once the proposed color change has been tested and confirmed to improve visibility, submit the solution to the repository owner or relevant stakeholders for implementation.

![2024-05-16 01_08_44-Window](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/109462746/db545924-7f68-4f55-aefa-f31a281401bf)
![2024-05-16 01_09_36-Window](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/109462746/ca2fde25-ce50-4805-b70a-8b0946371094)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by kvdevlopment** [comment]
Hello @Durgesh4993 

Sir,Please Assignee me this issue

**Comment by atharvarekhawar** [comment]
hey @Durgesh4993 , I would like to contribute to this issue if no is working on it currently.
