### ISSUE TITLE
Fixed top Navbar

### ISSUE THREAD

**Issue by Priya-49** [ChromeGaming/Community-Page#108]
### 🎮 feature Request

I would like to fix the top navbar so that it would be visible even upon scroll.

### Select program in which you are contributing

GSSOC

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayushrskiaa** [comment]
@Durgesh4993  I can do that please assign me.

**Comment by Priya-49** [comment]
I have done the task and made a PR.

**Comment by ayushrskiaa** [comment]
is it merged?
