### ISSUE TITLE
[New Feature]: DROP DOWN NAV BAR

### ISSUE THREAD

**Issue by IpsitaPrusty** [ChromeGaming/Community-Page#110]
### 🎮 feature Request

feature logic and basic description
The nav bar is static, when we scroll down the page the nav bar will also come. 

please @Durgesh4993 sir, assign this to me under GSSOC'24.

### Point down the features

feature points
it will continuously show the nav bar when we scroll up and down.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@IpsitaPrusty Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by IpsitaPrusty** [comment]
> @IpsitaPrusty Could you please explain more what you want to do, if possible you can also add screenshot.

Sure @Durgesh4993 sir, There is a navbar on the first page right, 
<img width="242" alt="foo" src="https://github.com/GameSphere-MultiPlayer/Community-Page/assets/145246053/147f706a-131c-48cd-aa84-aca2fd147dbd">

inside the navbar there are some elements so, when we hover on that button it will come with a box for better user's settings and notifications. From user's point of view it will be helpful in different ways:
-Easy access
-organized structure
-interactive elements and so on.

please @Durgesh4993 sir assign this to me.

**Comment by K-21** [comment]
@Durgesh4993 please assign this to me

**Comment by Aashka19** [comment]
plz assign it to me

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and I would love to contribute, can you please assign me this issue.
