### ISSUE TITLE
[Bug]: Footer section is not visible properly in the light mode

### ISSUE THREAD

**Issue by ayushrskiaa** [ChromeGaming/Community-Page#122]
### Give a brief about the bug ✍️

The text colour of the footer section of the home page is not visibe clearly. I want to change the text colour.

### What is the expected behavior? 🤔

I will change the Text colour to the black then it will be visible properly

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayushrskiaa** [comment]
Assign it to me

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Siddhi561** [comment]
Hey, can you please assign me this issue if it is not solved? This is my first time making an open-source contribution, and I really want to showcase my skills. I am very familiar with languages like Java, HTML, CSS, and JS. Apart from coding, I'm an ux/ui freelancer as well.

**Comment by Manaregr8** [comment]
> Hey, can you please assign me this issue if it is not solved? This is my first time making an open-source contribution, and I really want to showcase my skills. I am very familiar with languages like Java, HTML, CSS, and JS. Apart from coding, I'm an ux/ui freelancer as well.

Hi @Siddhi561, 

Identify issues in this repository, particularly focusing on responsiveness-related issues, which there are quite a few of. Once you spot them, I'll assign those issues to you.

**Comment by Siddhi561** [comment]
Okay thankyou @Manaregr8

**Comment by atharvarekhawar** [comment]
hey @Durgesh4993 @Manaregr8 , I want to contribute to this issue if no one is working on it.
