### ISSUE TITLE
[New Feature]: Development of a 404 Not Found Page / Error Page

### ISSUE THREAD

**Issue by sambitsingha** [ChromeGaming/Community-Page#142]
### A 404 Not Found page is essential if a link is missing or if somehow a page doesn't render due to any circumstances.

I would like to contribute to it under GSSoC'24

### Point down the features

A 404 page will let users know that the page is missing somehow or the feature has not been implemented yet. If the link suddenly gets abrupt , users may think the website is faulty , which will hamper user experiance.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sambitsingha** [comment]
@Durgesh4993 kindly check this out

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Dovineowuor** [comment]
I would like to formally request that you assign me to the task  #142. I kindly ask that you provide any related designs, motivations, or specific page features to help guide my work on this project.

**Comment by sambitsingha** [comment]
This issue is connected with Issue #187 , both of which I am working on. 

Clarified if any problem.

**Comment by Dovineowuor** [comment]
Thank you for this info
