### ISSUE TITLE
[Bug]: Footer links not visible on hover in light mode

### ISSUE THREAD

**Issue by AtharvKasar04** [ChromeGaming/Community-Page#143]
### Give a brief about the bug ✍️

When we enter the Light mode, the links in the footer becomes white, hence making them not visible and which is not a good point in terms of the website's aesthetics.

@Durgesh4993 Can you please assign me this issue under GSSoC'24? Thank You!

### What is the expected behavior? 🤔

it should become opposite so that the links are visible to give the feedback of being hovered.

### Provide step by step information reproduce the bug 📄

- Go in light more
- hover on the links in the foooter
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/108543702/b3961fb9-db23-4865-99d7-cb638d717c25)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
@AtharvKasar04 contribute considering the color palette used throughout website.

**Comment by Varshajha5** [comment]
@Durgesh4993 assign this issue to me

**Comment by Durgesh4993** [comment]
@Varshajha5 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
