### ISSUE TITLE
[Bug]: Responsiveness of navbar

### ISSUE THREAD

**Issue by Ridhima10** [ChromeGaming/Community-Page#147]
### Give a brief about the bug ✍️

The navbar is not responsive

### What is the expected behavior? 🤔

Navbar should be according to different screen sizes

### Provide step by step information reproduce the bug 📄

I will fix it according to 3 screens majorly- desktop, mobile and tablet

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
Hi @Ridhima10,

Feel free to tackle it. I've classified it as level 3 due to numerous related bugs. Please ensure you address all of them.

Thank you.

**Comment by Manaregr8** [comment]
@Ridhima10 Any update?

**Comment by Ridhima10** [comment]
@Manaregr8 There was some issue related electricity and I had final exams due to which I wasn't able to do it  but now it's done.. I'll start it today only and deliver as soon as possible. Sorry for inconvenience

**Comment by Manaregr8** [comment]
> @Manaregr8 There was some issue related electricity and I had final exams due to which I wasn't able to do it but now it's done.. I'll start it today only and deliver as soon as possible. Sorry for inconvenience

No problem just look into it as soon as you can.

**Comment by Manaregr8** [comment]
hi @Ridhima10 ,

Any Update?

**Comment by Ridhima10** [comment]
@Manaregr8  Working on it. Its whole tech stack has been changed that's why its taking time

**Comment by Priya-49** [comment]
@Manaregr8
The nabar is already made rsponsive as per ur request. It is already merged in PR #258 
![Screenshot 2024-05-31 111135](https://github.com/ChromeGaming/Community-Page/assets/118010930/b794e5cd-4bd7-43f7-852b-e5a15866aa3f)

**Comment by Ridhima10** [comment]
@Manaregr8  it's done. I just need to push it

**Comment by Manaregr8** [comment]
> @Manaregr8 it's done. I just need to push it

Nicely Done!
