### ISSUE TITLE
[New Feature]: Redesigning the home page

### ISSUE THREAD

**Issue by anuza08** [ChromeGaming/Community-Page#16]
### 🎮 feature Request

feature logic and basic description

### Point down the features

feature points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Aleena-Memon** [comment]
please assign me this task so i can work on it under GSSOC24

**Comment by Durgesh4993** [comment]
Could you please explain more what you want to do, if possible you can also add screenshot.

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by drick-infinity** [comment]
assign this issue to me as i  learned mern stack development i will create home page as well

**Comment by anuza08** [comment]
> Could you please explain more what you want to do, if possible you can also add screenshot.
> 
> If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...
> 
> Thank you :)
![Screenshot 2024-05-14 003117](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/98256478/0c1095ab-57cd-422b-bf51-7d9e664a2a6c)

@Durgesh4993 this is my idea , I can also keep the bg jst black as prev one without adding img , let mew know.
