### ISSUE TITLE
[Bug]: The products page has navbar at two places

### ISSUE THREAD

**Issue by Qanta-31** [ChromeGaming/Community-Page#163]
### Give a brief about the bug ✍️

Description
On the products page, the navbar is at two places- the header and the footer.
![Navbar at 2 places on products page](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/149178256/a3ae168e-6529-496f-8d26-0a2a2127b0df)

### What is the expected behavior? 🤔

Description
The navbar should only be at the top of the webpage and for better user experience it can be fixed at the top.

### Provide step by step information reproduce the bug 📄

Description
By styling the navbar properly.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Qanta-31** [comment]
@Durgesh4993 could you please assign this to me, I would be happy to work on it.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Qanta-31** [comment]
@Durgesh4993 Thank you for assigning.

**Comment by Qanta-31** [comment]
@Durgesh4993 someone has already updated it without being assigned to this particular task.

**Comment by Durgesh4993** [comment]
@Qanta-31 I have assigned you for design the product section

**Comment by Qanta-31** [comment]
Ok, on it
