### ISSUE TITLE
[Bug]: The social media icons on the About Us page are overlapping with the footer line.

### ISSUE THREAD

**Issue by Qanta-31** [ChromeGaming/Community-Page#171]
### Give a brief about the bug ✍️

Description
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/149178256/20fc40ee-6a46-48d2-ac15-cf5100b2b937)

### What is the expected behavior? 🤔

Description
the icons should not overlap with the footer line

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by annoy004** [comment]
can you assign me this issue
