### ISSUE TITLE
[Bug] : Footer tabs under "Info" section navigating incorrectly

### ISSUE THREAD

**Issue by Samridhi002** [ChromeGaming/Community-Page#175]
**Issue Description:**
I'm reporting an issue with the navigation behavior of the tabs under the "_Info_" section in the footer section of home page

**Affected Tabs:**

- Play Games
- Products
- Contribute

**Issue:**
When clicking on any of the tabs listed above under the "Info" section in the footer, they are incorrectly navigating to the index.html page (homepage) instead of their respective intended pages.

**Steps:**

Visit the Community Page website.
Scroll down to the footer section.
Click on any of the tabs under "_Info_" (except "_Home_" and "_About Us_" ).

**Expected Behavior:**
Each tab should navigate to its corresponding webpage. For example, "_Play Games_" should go to the games page, "_Products_" should go to the products page, and so on.

**Actual Behavior:**
Regardless of which tab is clicked under "_Info_" (except " _Home_ " and "_About Us_"), it navigates to the index.html page, which is likely the homepage.

**Attachments**

![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/169380578/858ecfdc-177b-4c0d-9f31-ce5a0ee892b2)

![Screenshot (2)](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/169380578/84086ecb-f039-462d-b226-27f468eff6fc)

Hii PA, I can solve this issue once you assign me under GSSoC. Thank you!

### What is the expected behavior? 🤔

**Expected Behavior:**
Each tab should navigate to its corresponding webpage. For example, "_Play Games_" should go to the games page, "_Products_" should go to the products page, and so on.

### Provide step by step information reproduce the bug 📄

**Steps to find solution:**
In the index.html file, under the footer section we just need to change the file name for each tab (except  Home and About Us ) to its respective file. 
for every tab link, we need to update href attribute to correct file name

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Vaibhavtech2006** [comment]
[@](https://github.com/ChromeGaming/Community-Page/issues/175)assigned this work to me

**Comment by Vaibhavtech2006** [comment]
@Durgesh4993 assigned this work to me
