### ISSUE TITLE
Add hover highlight effect and improve visibility in light mode for click-to-play button & click here button(below)

### ISSUE THREAD

**Issue by tanya-54** [ChromeGaming/Community-Page#179]
### Give a brief about the bug ✍️

I noticed a couple of issues with the click-to-play button in the play games section:

Hover Highlight Effect:
The button does not highlight when hovered over. Adding a hover effect would improve the user experience by providing visual feedback.

Visibility in Light Mode:
In light mode, the click-to-play and click-here buttons are not clearly visible. This affects usability, as users may not easily identify these interactive elements.

screenshot:
![Screenshot 2024-05-23 204713](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/148340088/c780048c-8bf9-4a3a-ac41-c25b825b9829)

assign me this issue so that the games section will interact with user efficiently  [Durgesh4993](https://github.com/Durgesh4993)

### What is the expected behavior? 🤔

Expected Behavior:

The button should visually highlight (e.g., change color, border, or scale) to indicate it is interactive.
The buttons should be clearly visible in both light and dark modes.

Actual Behavior:

The button does not change visually when hovered over.
The buttons are not clearly visible in light mode

### Provide step by step information reproduce the bug 📄

Steps to Reproduce:

- Go to the play games section.
- Hover over the click-to-play button.
- Switch to light mode and observe the click-to-play and click-here buttons.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Deepthi-Ramineni** [comment]
Can you please assign this to me?

**Comment by Durgesh4993** [comment]
@tanya-54 change gif into white also

**Comment by Durgesh4993** [comment]
@Deepthi-Ramineni Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
