### ISSUE TITLE
[Bug]: Burger Menu is not visible in light mode responsive

### ISSUE THREAD

**Issue by dhruv8433** [ChromeGaming/Community-Page#188]
### Give a brief about the bug ✍️

@GameSphere-MultiPlayer

here when we toggle to responsive mode, the burger menu icon is not visible in light mode

### What is the expected behavior? 🤔

Description

you can check this out this is light mode image
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/114583978/f8259b53-568f-4c92-a175-ad12be5645bf)

dark mode image with toggle menu
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/114583978/95d97514-3689-4500-b3c9-b4ca5f66b7df)

### Provide step by step information reproduce the bug 📄

Description

we can change color of toggle menu in light mode

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)

**Comment by dhruv8433** [comment]
sure :)

**Comment by dhruv8433** [comment]
@Durgesh4993 

check #213 and merge it
