### ISSUE TITLE
[Bug]:  "Join Now" Not Visible

### ISSUE THREAD

**Issue by aursh24** [ChromeGaming/Community-Page#211]
### Give a brief about the bug ✍️

Description:
The text "Join Now" in the button is not visible on the Sticky Element in Dark Mode.

Screenshot of the Issue:
 
![Screenshot 2024-05-26 094946](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121930064/601a5f35-5951-4ea9-a33c-62ccfeda9e7f)

### What is the expected behavior? 🤔

Description:
The text should be visible by default without hovering the mouse over it to turn it Blue.

### Provide step by step information to reproduce the bug 📄

Description:
Open The Home Page of Chrome Gaming in Dark Mode.
Check the Sticky Element Containing Join Now Button for the Discord Server.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by aursh24** [comment]
please assign me this issue under GSSoC24

**Comment by Manaregr8** [comment]
Hi @aursh24,

After merging your pull request, we noticed a bug. If you click on the switch theme button twice, you'll encounter something like in the image below. Please resolve this issue. If you need assistance, don't hesitate to ask.

Thank you.
![dsdsdsddsxsx](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/99804338/f674012b-9896-4b28-b53b-cd1061eb4f3a)

**Comment by aursh24** [comment]
done with the changes please refer to #241

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!
