### ISSUE TITLE
[New Feature]: Adding footer section in product , play games ,contribute pages

### ISSUE THREAD

**Issue by agastya3636** [ChromeGaming/Community-Page#216]
### 🎮 feature Request

Adding footer section in product , play games ,contribute pages as currently the don't have footer section.

### Point down the features

Adding footer section in product , play games ,contribute pages
![image](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/124435030/a4df1952-d3b6-478d-b0f2-c544c700c87f)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Dovineowuor** [comment]
Hello @agastya3636 can you assign this to me?
