### ISSUE TITLE
[Bug]: Social Icon Linking 

### ISSUE THREAD

**Issue by aursh24** [ChromeGaming/Community-Page#228]
### Give a brief about the bug ✍️

The Social Icons consisting of "Twitter" or "X" is not redirecting to the Chrome Gaming Twitter Page instead it's linking to the Home page of Twitter. 

### What is the expected behavior? 🤔

After clicking on the "Twitter" Social Icon it should redirect and show the Chrome Gaming Twitter handle.

### Provide step by step information to reproduce the bug 📄

Go the the home page of Chrome Gaming
On the extreme left of the screen you will get multiple Social Icons consisting of Youtube handle, Facebook, Instagram, Twitter etc.
Click on the Twitter and it will be redirecting you to the Twitter Home Page instead of Chrome Gaming Twitter Handle.

Screenshot Attested: 

![socialIcons](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121930064/d27b225c-252f-43fa-b8a3-bf0a1c95cf27)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by aursh24** [comment]
please assign me this issue under GSSoC24.

**Comment by Priyamjain1105** [comment]
Hi @aursh24 ,

I'd like to work on issue #228. Can you please assign it to me?

Thanks
