### ISSUE TITLE
[Enchancement]: Fixing the visibility of the join now button after switching to dark mode

### ISSUE THREAD

**Issue by CodeXsubham** [ChromeGaming/Community-Page#231]
### Give a brief about the bug ✍️

![Screenshot 2024-05-28 132153](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/119094596/1a182b40-9eba-4e25-a5b9-c1d81335573c)
 There is  no Visibility of the Join now Button in the Dark mode after Switching the modes...

**Features I would Add as the Gssoc'24 Contributor**

- Smooth Hover effect 
- Visibility Of the Button

### Select Program in which you are contributing.
**GssoC'24**

### Code of Conduct
✔️ I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/issues/222) of this project.

**Comment by Priyamjain1105** [comment]
Hi @CodeXsubham ,

I'd like to work on issue #231. Can you please assign it to me?

Thanks

**Comment by lassmara** [comment]
please assign me this issue

**Comment by GeeekySouro003** [comment]
hey can u please assign me this issue

**Comment by AdityaKumar-2501** [comment]
Hey, could you please assign me this issue under gssoc

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!
