### ISSUE TITLE
[New Feature]: Buttons are not designed in play.html page

### ISSUE THREAD

**Issue by vishal02527** [ChromeGaming/Community-Page#232]
### 🎮 feature Request

@Durgesh4993 I saw your project and it's superb. Although I got a major issue that buttons are not designed in the play.html page.

See the below screenshot:

![Screenshot 2024-05-28 144303](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/135222259/97b584df-9d02-4373-8ef8-3a57a3876505)

### Point down the features

I can definitely make these two buttons more beautiful that will be suitable according to your website.

Please add labels on this issue and then assign this issue to me under GSSoC'24. 
I would be happy to contribute in your lovely project.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Priyamjain1105** [comment]
Hi @vishal02527 ,

I'd like to work on issue #232. Can you please assign it to me?

Thanks

**Comment by Manaregr8** [comment]
I've added a level 2 badge to achieve a nice animated button. Depending on the appearance of the button, I'll switch it to level 1 if it doesn't align with level 2.

Thank you.

**Comment by vishal02527** [comment]
@Manaregr8 Thanks for assigning me to this issue. I will definitely create the same animated buttons for getting label2 that you expect to be.
