### ISSUE TITLE
[Documentation Bug]: New documentation to setup The Nodejs backend

### ISSUE THREAD

**Issue by sambitsingha** [ChromeGaming/Community-Page#251]
### Describe the bug ✍️

New documentation needs to be made for other contributors to setup the project for Nodejs backend.

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sambitsingha** [comment]
@Durgesh4993 I am doing this , but with that merge that PR for the initial file structure

**Comment by Durgesh4993** [comment]
Add a output demo vedio

**Comment by sambitsingha** [comment]
@Durgesh4993 Alr I will add a demo video no worries.

**Comment by sambitsingha** [comment]
@Durgesh4993 I have already done this with the previous PR. So what to do with this one ?
