### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by Aditi-P22** [ChromeGaming/Community-Page#26]
### 🎮 feature Request

This feature proposes the addition of a "Back to Top" button functionality to enhance user experience in navigating through lengthy pages within the project. The "Back to Top" button would allow users to swiftly return to the beginning of the page, offering convenience and improved usability.

### Point down the features

The proposed solution involves implementing a visually discreet yet easily accessible button, positioned at the bottom right corner of the viewport. Upon clicking or tapping, the button smoothly scrolls the page back to the top, providing a seamless navigation experience. The button's design will align with the project's aesthetic principles while maintaining clarity and functionality.
<img width="960" alt="gssoc 3" src="https://github.com/GameSphere-MultiPlayer/Community-Page/assets/106650588/a4f914f1-5510-4237-b13f-d84499ebd499">

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Aditi-P22** [comment]
Please assign me this issue under GSSoC'24.

**Comment by Aleena-Memon** [comment]
Please assign me this issue , so i can work on it under GSSoC'24.

**Comment by Durgesh4993** [comment]
@Aleena-Memon Please raise any other issue, i'll assign you

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by drick-infinity** [comment]
As I learned MERN stack development i easily create this issue assign to me

**Comment by atharvarekhawar** [comment]
hey @Durgesh4993 , I would like to contribute to this issue if no one is working on it currently.

**Comment by atharvarekhawar** [comment]
Hello @Durgesh4993 , It has been a month for this issue and not resolved yet , please assign it to me I will create PR within 1 day.
