### ISSUE TITLE
New feature Dark mode can be added 

### ISSUE THREAD

**Issue by ivarcodes** [ChromeGaming/Community-Page#261]
### 🎮 feature Request

Dark mode feature can be added to site 

### Point down the features

Dark mode feature can be added to site so it doesn't hurt the eyes of viewer 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Tanishka023** [comment]
Hey!! I am excited to contribute to this project, please assign this to me @ivarcodes
