### ISSUE TITLE
[New Feature]: Adding Scroll Reveal feature 

### ISSUE THREAD

**Issue by sambitsingha** [ChromeGaming/Community-Page#262]
### 🎮 feature Request

Adding scroll reveal feature on the website makes look cool while scrolling.

### Point down the features

This will be done by adding a ScrollRevealJs library . The js file for it can be customised afterwards when new pages are added.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@sambitsingha Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by sambitsingha** [comment]
@Durgesh4993 


https://github.com/ChromeGaming/Community-Page/assets/110420002/e4a57845-f7e8-49f6-a4de-cd7750ff84c2

Like this
