### ISSUE TITLE
[Bug]: Improve the responsiveness

### ISSUE THREAD

**Issue by Sambit-Mondal** [ChromeGaming/Community-Page#264]
### Give a brief about the bug ✍️

In mobile devices (small devices), the responsiveness is not that great. The logo goes out of display, as well as the Social icons overlap the other content. This makes the webpage clumsy.

![Screenshot 2024-05-31 102200](https://github.com/ChromeGaming/Community-Page/assets/138088550/f10c0336-6a49-4350-8ea9-b7063bce3856)

### What is the expected behavior? 🤔

THe webpage UI should be clean enough and the content should be clearly visible, along with the icons properly aligned so as to provide a great User Experience.

### Provide step by step information to reproduce the bug 📄

1. Open the webpage.
2. Go to inspect.
3. Lower the width of the screen to that of small screens.
4. You'll get to see the issue.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Sambit-Mondal Take your time

**Comment by Sambit-Mondal** [comment]
@Durgesh4993 Thank you Sir!

**Comment by Sambit-Mondal** [comment]
Also, @Durgesh4993 Sir could you please provide me the Discord server link once more, I forgot to join it, and now it seems that I've somehow lost the link :)
