### ISSUE TITLE
[New Feature]: Would u like to add favicon image to your website

### ISSUE THREAD

**Issue by Anjaliavv51** [ChromeGaming/Community-Page#266]
### 🎮 feature Request

feature logic and basic description

Wanted to add the logo image to the favicon of the website.

### Point down the features

feature points
![image](https://github.com/ChromeGaming/Community-Page/assets/154777864/3f77e937-2a50-4681-9c87-6df524e01508)

instead of chrome symbol and image will be added.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Anjaliavv51 Please raise any other issue, because someone is already working on it...
