### ISSUE TITLE
[Bug]: Share button is not working in Contribute page 

### ISSUE THREAD

**Issue by Yashgabani845** [ChromeGaming/Community-Page#276]
### Give a brief about the bug ✍️

Description

Share button is not working on any other page except home page 
this should be the expected behaviour of share button on clicking 
![Screenshot (253)](https://github.com/ChromeGaming/Community-Page/assets/127788321/309514ac-b5ce-46d0-9611-997b85d848d7)

but it is not responding on other pages 

### What is the expected behavior? 🤔

Description
it should be open on clicking and show all 4 options 

### Provide step by step information to reproduce the bug 📄

Description
 i will the logic to the each pages so that it will work smooth

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Yashgabani845** [comment]
@Durgesh4993  please assign me this issue

**Comment by vaibhavi-singh-673** [comment]
can you assign me the issue i can work on it @Durgesh4993

**Comment by Yashgabani845** [comment]
@vaibhavi-singh-673 please work on other issues I have found, raised it
