### ISSUE TITLE
[New Feature]: Cursor trail feature

### ISSUE THREAD

**Issue by Sambit-Mondal** [ChromeGaming/Community-Page#281]
### 🎮 feature Request

A Gaming community webpage without some attractive RGB features, is just like a big ocean without water :)
So, I want to add a Cursor trail animation feature, which will surely increase the attractiveness of the UI by a huge margin.

### Point down the features

The cursor trail animation will work when the user will move the mouse pointer throughout the screen, and also, there'll be a special animation when the mouse pointer is stopped and is rested at once place. It'll attract the user's attention and improve the attractiveness of the whole UI.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
Hi @Sambit-Mondal,

Make it look visually appealing.
Thank You

**Comment by Sambit-Mondal** [comment]
@Manaregr8 Okay, thank you!
