### ISSUE TITLE
[New Feature]: Adding Hover effect

### ISSUE THREAD

**Issue by Sambit-Mondal** [ChromeGaming/Community-Page#282]
### 🎮 feature Request

There's no Hover effect in the Play Games page, which lowers the UI attractiveness, and makes the page a bit unattractive.

https://github.com/ChromeGaming/Community-Page/assets/138088550/8cea55cf-63b3-40cf-b38d-77f63fc6de0e

### Point down the features

I want to add a Hover effect to the buttons in the Play Games page, so as to make the page more attractive to the users, give them a better User Experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
Hi @Sambit-Mondal,
Currently buttons are being worked upon in a issue If Hover effect will not be there i will reopen this issue.

Till then keep exploring and dig more issues.

Thank You

**Comment by Sambit-Mondal** [comment]
@Manaregr8 Okay!
