### ISSUE TITLE
[Documentation Enhancement]: Updating readme.md

### ISSUE THREAD

**Issue by Abhigna-arsam** [ChromeGaming/Community-Page#284]
### Describe the bug ✍️

no bug

The current README lacks visual appeal and comprehensive information, making it challenging for users to quickly grasp the project's technology stack, features, and structure.

### Provide step by step information reproduce the bug 📄

I propose updating the README by adding tech stack logos to visually represent the technologies used, add some description of the project , and including a table of contents for easy navigation.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Abhigna-arsam** [comment]
@Durgesh4993 please assign this work to me

**Comment by Durgesh4993** [comment]
@Abhigna-arsam Could you please explain more what you want to do

**Comment by Abhigna-arsam** [comment]
@Durgesh4993 I propose to add overview,techstack ,with logos in addition to it table of content for easy navigation in readme.md
