### ISSUE TITLE
[New Feature]: Implement a dark mode toggle

### ISSUE THREAD

**Issue by ananyag309** [ChromeGaming/Community-Page#289]
### 🎮 feature Request

To include Dark Mode Toggle

### Point down the features

here's why including a dark mode toggle could be beneficial:

Improved User Experience: Dark mode enhances readability and reduces eye strain, making the community page more user-friendly.

Customization Options: Users can switch between light and dark modes based on their preferences, improving accessibility and catering to diverse needs.

Aesthetic Appeal: Dark mode can give the community page a modern and sleek appearance, potentially attracting more users.

Energy Efficiency: Dark mode reduces the amount of light emitted by screens, potentially extending battery life for users accessing the community page on mobile devices.

Alignment with Trends: Many users expect dark mode options in modern applications, ensuring the community page stays current and competitive.

Accessibility Considerations: Dark mode can make the content more accessible for users with visual impairments or sensitivity to bright lights, promoting inclusivity.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ananyag309** [comment]
@Durgesh4993 sir, please assign this issue to me.

**Comment by Aditya6112** [comment]
I can solve this issue. Please assign it to me.

**Comment by Durgesh4993** [comment]
@Aditya6112 Could you please explain more what you want to do, we already have dark mode toggle

**Comment by Aditya6112** [comment]
Before:
<img width="405" alt="1gssoc" src="https://github.com/ChromeGaming/Community-Page/assets/93546421/500cd080-34c7-4349-b3b9-07b3e0a1f3ed">

After:
<img width="388" alt="2gssoc" src="https://github.com/ChromeGaming/Community-Page/assets/93546421/75c746bd-ea60-416e-b221-5911d4a6a8a5">

If the community page already includes a dark mode toggle, it's important to highlight this feature to users, ensuring they are aware of its availability and benefits. Additionally, continuous improvement based on user feedback can further enhance the dark mode experience.

**Comment by Aditya6112** [comment]
> @Aditya6112 Could you please explain more what you want to do, we already have dark mode toggle


Before:
<img width="405" alt="1gssoc" src="https://github.com/ChromeGaming/Community-Page/assets/93546421/500cd080-34c7-4349-b3b9-07b3e0a1f3ed">

After:
<img width="388" alt="2gssoc" src="https://github.com/ChromeGaming/Community-Page/assets/93546421/75c746bd-ea60-416e-b221-5911d4a6a8a5">

If the community page already includes a dark mode toggle, it's important to highlight this feature to users, ensuring they are aware of its availability and benefits. Additionally, continuous improvement based on user feedback can further enhance the dark mode experience.

**Comment by ananyag309** [comment]
@Durgesh4993 sir i raised the issue weeks ago, if it is needed then please assign it to me. Recently i have done for one website too
![tog](https://github.com/ChromeGaming/Community-Page/assets/145869907/8e852c0c-3542-42f6-bb7f-c35bf27bc017)
![togg](https://github.com/ChromeGaming/Community-Page/assets/145869907/3e24f1ed-c641-44aa-ad19-c3b40a799efb)
