### ISSUE TITLE
[New Feature]: Contact Form

### ISSUE THREAD

**Issue by ananyag309** [ChromeGaming/Community-Page#290]
### 🎮 feature Request

Including contact form

### Point down the features

Implement a simple contact form using HTML's <form> tag to allow users to send inquiries, suggestions, or feedback directly from the community page.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ananyag309** [comment]
@Durgesh4993 please have a look, and if need a contact form kind thing then please assign the issue to me.

**Comment by Aditya6112** [comment]
I can help with this issue.This same thing I have done in my portfolio in contact section. Please have a look on it.
link: https://adityaraj-portfoliosite.netlify.app/
Thanks

**Comment by Manaregr8** [comment]
> @Durgesh4993 please have a look, and if need a contact form kind thing then please assign the issue to me.

Hi @ananyag309,

A contact form would be nice, but having a Discord channel for queries seems to satisfy that need. Instead, I think a suggestion form and a newsletter would be great additions. What are your thoughts on this? If you're up for it, I will assign this issue to you.

Thank you!

**Comment by ananyag309** [comment]
@Manaregr8 yes though discord seems to satisfy that need we can create a suggestion/feedback form which can help user directly interact through the community page. I will try to add newsletter as well. thank you for assigning the issue.

**Comment by ananyag309** [comment]
it's not yet complete i will add more details and style to it , i design a basic form. i kept is simple so that it match with the the page. if you liked it i shall continue 

![queerr](https://github.com/ChromeGaming/Community-Page/assets/145869907/dcc2f5ac-408a-4335-b931-5b6882e528c1)

**Comment by Vaibhavtech2006** [comment]
@Durgesh4993
I can help with this issue.This same thing I have done in my portfolio in contact section. Please have a look on it. this not complete i will help it to complete this issure
