### ISSUE TITLE
[New Feature]: Navbar is not visible

### ISSUE THREAD

**Issue by Aditya6112** [ChromeGaming/Community-Page#291]
### 🎮 feature Request

Navbar is not visible when I cloned my project on my local.
After hovering It is visible.
<img width="959" alt="Screenshot 2024-06-03 125420" src="https://github.com/ChromeGaming/Community-Page/assets/93546421/ad06ee36-0108-4eb7-9f45-fbd5bd023e89">

### Point down the features

We can change the background color that align with the body color or implement a light/dark mode toggler button on the page.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Aditya6112** [comment]
@Durgesh4993  I can solve the issue Please assign it to me.

**Comment by Aashka19** [comment]
@Durgesh4993 I can solve the issue
Please assign it to me under gssoc 24
