### ISSUE TITLE
[New Feature]:  Add games in the webpage

### ISSUE THREAD

**Issue by Bhavishya2601** [ChromeGaming/Community-Page#293]
### 🎮 feature Request

I want to add games in the product page 

Hope you would assign this task to me

### Point down the features

This would have the webpage look attractive

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Bhavishya2601 Could you please explain more what you want to do

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!

**Comment by Bhavishya2601** [comment]
> @Bhavishya2601 Could you please explain more what you want to do

so what I want to do is in the play games page, we can actually create div's (Sections) like 3 in a row for the games with there picture, name and the link to the game, we can add the games of your other repo's like squard-line, information absent , dot-box etc.
![Screenshot 2024-06-05 180726](https://github.com/ChromeGaming/Community-Page/assets/147748752/43a2b933-70ef-40ae-8936-2b1e6675c05f)

also on every page, the same styling doesn't look good (gif with some text on the side), it makes the website less attractive

**Comment by Bhavishya2601** [comment]
pls assign this task to me

**Comment by Bhavishya2601** [comment]
@Durgesh4993 
 check it out

**Comment by Manaregr8** [comment]
Any progress? @Bhavishya2601

**Comment by Bhavishya2601** [comment]
sorry @Manaregr8, I was stuck in some matter, now it's over, I will complete this issue as soon as possible
