### ISSUE TITLE
[Bug]: Leaderboard isn't visible

### ISSUE THREAD

**Issue by Sambit-Mondal** [ChromeGaming/Community-Page#295]
### Give a brief about the bug ✍️

The leaderboard isn't visible, while we sroll down to the leaderboard section.

![Screenshot 2024-06-04 094127](https://github.com/ChromeGaming/Community-Page/assets/138088550/ce236042-590a-4570-acaf-eb9947772f1e)

### What is the expected behavior? 🤔

The leaderboard should've been clearly visible.

### Provide step by step information to reproduce the bug 📄

1. Open the website
2. Scroll down to the leaderboard section
3. You'll see the data isn't visible

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!

**Comment by Manaregr8** [comment]
any progress? @Sambit-Mondal

**Comment by Sambit-Mondal** [comment]
@Manaregr8 Yeah, I'm working on this... I went for a trip recently, so I wasn't able to contribute much, I'm sorry for that. But I'm back now, and trying to finish this asap! 

Thank you!
