### ISSUE TITLE
Adding FAQ section and Fully Responsive Website 

### ISSUE THREAD

**Issue by gupta-ritik** [ChromeGaming/Community-Page#30]
### 🎮 feature Request

feature logic and basic description
Adding FAQ section with drop down.
Mobile friendly website 

### Point down the features

feature points
1. FAQ section 
2. Responsive 
3. Hover Effect 
4. Adding Favicon 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by gupta-ritik** [comment]
@Durgesh4993 please assign this task to me.

**Comment by kanikaa-3018** [comment]
please assign me this issue for GSSoc'24, i have expertise in this field and can handle the issue

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by gupta-ritik** [comment]
Please merge the PR as soon as possible

**Comment by gupta-ritik** [comment]
And also close the PR @Durgesh4993
