### ISSUE TITLE
[Bug]: Toggle button is not on home page

### ISSUE THREAD

**Issue by Ridhima10** [ChromeGaming/Community-Page#301]
### Give a brief about the bug ✍️

The toggle button to switch theme is not on home page
![Screenshot 2024-06-07 094457](https://github.com/ChromeGaming/Community-Page/assets/85826117/ddd8e9b8-02d7-46a7-aa3a-20a7d773de21)

### What is the expected behavior? 🤔

It should be added on home page as well just like other pages

### Provide step by step information to reproduce the bug 📄

I will add it to the home page

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
Hi @Ridhima10,
Sorry for any inconvenience caused due to my inactivity because of exams.

Thank You
