### ISSUE TITLE
[Bug]: Elements leaking out of the welcome box in the home page

### ISSUE THREAD

**Issue by arpy8** [ChromeGaming/Community-Page#303]
### Give a brief about the bug ✍️

The elements are leaking out of the welcome box in the home page. Also the close button is not functioning for this container.

### What is the expected behavior? 🤔

The elements should be present inside the pop up

### Provide step by step information to reproduce the bug 📄

Bug is visible on the home page

attaching screenshot for reference:
![image](https://github.com/ChromeGaming/Community-Page/assets/74809468/d345cc9f-df0f-47c0-a638-41e07dc42a67)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Vaibhavtech2006** [comment]
@arpy8 plz assigned this work to me
