### ISSUE TITLE
[New Feature]: Animated cursor

### ISSUE THREAD

**Issue by Ridhima10** [ChromeGaming/Community-Page#320]
### 🎮 feature Request

I would like to add animated cursor feature
It will enhance the UI of the website

### Point down the features

Like this.

https://github.com/ChromeGaming/Community-Page/assets/85826117/26eb10aa-4d3b-4df8-8a00-465ef37f55ae

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Ridhima10** [comment]
@Manaregr8 Thankyou for assigning me this issue.
This is an advance level task since i need to write function for the coordinates and add the styles as well. Please review it once and assign it to level 3 if you find it  advance too as well

**Comment by Manaregr8** [comment]
hi @Ridhima10 ,

Go for it

**Comment by Ridhima10** [comment]
@Manaregr8  Thankyou so much
