### ISSUE TITLE
[New Feature]: Design Products page

### ISSUE THREAD

**Issue by Ridhima10** [ChromeGaming/Community-Page#322]
### 🎮 feature Request

Only product page needs styling. I would like to style it
Also, I need to discuss with you like what content do you want me to put inside the cards?
I will take care of the styling but i need to know the content

### Point down the features

![Screenshot 2024-06-13 191401](https://github.com/ChromeGaming/Community-Page/assets/85826117/eb02e5fc-8f68-4851-9b1e-744b0759553e)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
For now, I don't have the details on what to add to the product page's card. I believe @Durgesh4993  will be the right person to guide you regarding that.

Let me know if you need any further adjustments!
