### ISSUE TITLE
[New Feature]: Hover effect on Nav-items 

### ISSUE THREAD

**Issue by Ridhima10** [ChromeGaming/Community-Page#323]
### 🎮 feature Request

I would like to change the hover effect on navbar items.
I does not look good as per the theme of website

### Point down the features

I will add a hover effect just like i did in the headings.
A minimal border below each item on hovering
Reference-
![Screenshot 2024-06-15 225246](https://github.com/ChromeGaming/Community-Page/assets/85826117/e8f3d1b9-7c8b-40ff-882e-f59105934f28)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
I will review the changes you want to make and approve them if they improve the navigation's alignment with the overall design.

Thank you.

**Comment by Manaregr8** [comment]
Nicely done @Ridhima10!
