### ISSUE TITLE
[Bug]: Chrome animation in smaller screens

### ISSUE THREAD

**Issue by Ridhima10** [ChromeGaming/Community-Page#332]
### Give a brief about the bug ✍️

In home page the chrome gaming animation is bigger than screen width for smaller screens (it should act like Play Games Page in smaller screens)

### What is the expected behavior? 🤔

Its size should be according to screen size

### Provide step by step information to reproduce the bug 📄

![Uploading Screenshot 2024-06-20 173102.png…]()

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Ridhima10** [comment]
@Manaregr8 Logo is in 2 pages :Home page as well as about page.
 When i'm trying to fix the logo in about page, I need to fix alignment of whole page since everything is overflowing. Kindly assign this as level 3 because i need to modify whole code for this.

![Screenshot 2024-06-21 171324](https://github.com/ChromeGaming/Community-Page/assets/85826117/46360f0a-e860-489e-945e-7660b9c7fda4)
![Screenshot 2024-06-21 171332](https://github.com/ChromeGaming/Community-Page/assets/85826117/ab953f47-d058-434a-a53e-885f10e78aff)


![Screenshot 2024-06-21 171341](https://github.com/ChromeGaming/Community-Page/assets/85826117/a7535f5c-7687-4fbb-ae74-ad3aa0a8b029)



It needs to be somewhat like this:
![Screenshot 2024-06-21 171258](https://github.com/ChromeGaming/Community-Page/assets/85826117/425e1cc1-6c57-4386-829d-3f3f3a549f2a)
![Screenshot 2024-06-21 171102](https://github.com/ChromeGaming/Community-Page/assets/85826117/b4473335-50fb-4b6c-a0df-8ebd43d41f45)
![Screenshot 2024-06-21 171134](https://github.com/ChromeGaming/Community-Page/assets/85826117/8671d3be-d29e-4451-af6c-1e7bedab9fe5)
![Screenshot 2024-06-21 171247](https://github.com/ChromeGaming/Community-Page/assets/85826117/6be6972e-b833-4e94-b06c-cfd2ada914d0)

**Comment by Ridhima10** [comment]
@Manaregr8  kindly review this

**Comment by Manaregr8** [comment]
> @Manaregr8 kindly review this

Nice Explaination! assigned level3, go for it.
