### ISSUE TITLE
[Bug]: css of light mode and difficulty in text visibility in products page footer in dark mode

### ISSUE THREAD

**Issue by NeerajaGurram** [ChromeGaming/Community-Page#335]
### Give a brief about the bug ✍️

issues :
- text in the footer(in products page) is not visible when switched to dark mode
- also there isn't much difference between light mode and dark mode(only the header and footer changes)
text in footer:
![image](https://github.com/ChromeGaming/Community-Page/assets/152693538/c3493d17-4a3a-4579-b733-504399421114)

in light mode:
![image](https://github.com/ChromeGaming/Community-Page/assets/152693538/ed54218d-e8f5-4c38-b3e4-2bf0d81c35c0)

in dark mode:
![image](https://github.com/ChromeGaming/Community-Page/assets/152693538/2fb9a59a-1316-4661-b7c1-6c299f386820)

### What is the expected behavior? 🤔

text in footer should be visible in any mode
the light mode is meant to have light colors rather than dark colors

### Provide step by step information to reproduce the bug 📄

i would like to make appropriate changes in the css to clear these bugs
i would like to work on this , please assign me this under gssoc'24 and give appropriate labels to the issue.
Thankyou

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
Hi @NeerajaGurram,

This issues is already being fixed in a different pre defined issue. I would suggest that you rather find more within repo and i will assign that to you.

Thank You.
