### ISSUE TITLE
[Bug]: The Home page footer Issue

### ISSUE THREAD

**Issue by MuraliDharan7** [ChromeGaming/Community-Page#337]
### Give a brief about the bug ✍️

Description:
Home page footer has issue which is the share button is colliding with the newsletter in the background.

### What is the expected behavior? 🤔

The newsletter in the background should not be there as in other websites.

### Provide step by step information to reproduce the bug 📄

This newsletter section needs to be deleted and the share button should be placed at the correct place as in other pages.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
I will like if newsletter section is not touched....and share buttons are aligned according to the proper flow, propose the issue accordingly.

Thank You

**Comment by MuraliDharan7** [comment]
> I will like if newsletter section is not touched....and share buttons are aligned according to the proper flow, propose the issue accordingly.
> 
> Thank You

I think this issue has been resolved by someone already. You can close this issue
