### ISSUE TITLE
[New Feature]: a better loader

### ISSUE THREAD

**Issue by NeerajaGurram** [ChromeGaming/Community-Page#340]
### 🎮 feature Request

a better relevant preloader can be set to the webpage

### Point down the features

current pre loader:

https://github.com/ChromeGaming/Community-Page/assets/152693538/1ef92fa5-b8e5-41e9-a553-4e51f4e461a5

pre loaders suggested:

![Animation - 1718978494744](https://github.com/ChromeGaming/Community-Page/assets/152693538/85ef8bed-c99d-414c-bfae-72c64f2e92de)

or

https://github.com/ChromeGaming/Community-Page/assets/152693538/296fabd0-3033-464e-a391-c62214c25fd8

i would like to work on this, please assign me this under gssoc and give appropriate labels
thankyou

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
the first suggested one will look great.

**Comment by NeerajaGurram** [comment]
@Manaregr8 
![image](https://github.com/ChromeGaming/Community-Page/assets/152693538/8a22f9d9-86d8-49d3-9e81-224c89001944)
sorry,
unfortunately i got know that this animations resolution is bad on increasing the size which can disturb the webpage look.
so i came up with some more suggestions(these loaders aren't animations , they are made using html and css , so no resolution problem)

1.

https://github.com/ChromeGaming/Community-Page/assets/152693538/71d8c148-f35a-45fc-b64d-eaa39da50b0b


2.

https://github.com/ChromeGaming/Community-Page/assets/152693538/c8334761-0358-4653-abc3-1ab006b66957

3.

https://github.com/ChromeGaming/Community-Page/assets/152693538/f0119467-5492-4218-9cfa-031ec58ef824

4.

https://github.com/ChromeGaming/Community-Page/assets/152693538/35dcf68f-57ef-443c-89b5-9f427df68ed8

Could you please choose one of these , which better suits the website.
Thankyou

**Note:** the actual size of these preloaders may vary and colors will also be changed according to the website theme :)

**Comment by NeerajaGurram** [comment]
@Manaregr8 plz choose one of the preloaders mentioned above, so I can make a PR .
Thankyou.
