### ISSUE TITLE
[New Feature]: Add Customers page

### ISSUE THREAD

**Issue by MuraliDharan7** [ChromeGaming/Community-Page#347]
### 🎮 feature Request

I Want to add customers page, where I can add some random customer (for example) and provide their reviews about the website in this page.

### Point down the features

feature points

I add the name, photo and the review text of the reviewers, which is customers.

![image](https://github.com/ChromeGaming/Community-Page/assets/130668745/9ca36830-c265-4891-b9f5-9beddf6df8d7)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
You talking about testimonials right?

**Comment by MuraliDharan7** [comment]
> You talking about testimonials right?

Yeah, that is what I am talking by the way
