### ISSUE TITLE
[Bug]: circle container in products page

### ISSUE THREAD

**Issue by NeerajaGurram** [ChromeGaming/Community-Page#360]
### Give a brief about the bug ✍️

there is a circle container on the nav bar of products project ( i don't think it has any purpose)
![image](https://github.com/ChromeGaming/Community-Page/assets/152693538/bc3e9acd-f32a-4539-ac4f-958617d3c138)

### What is the expected behavior? 🤔

it should be removed

### Provide step by step information to reproduce the bug 📄

i would like to remove it by making changes in products page
please assign me this under gssoc and give appropriate labels to it.
Thankyou.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and I would love to contribute, can you please assign me this issue.

**Comment by Manaregr8** [comment]
> Hi, I have been following your project and I would love to contribute, can you please assign me this issue.

@Soujanya2004 find new issues and will love to assign you those as this program is a first come first served based.

Thank You for following along.

**Comment by Manaregr8** [comment]
@NeerajaGurram, Basically that's not a container that's cursor animation you don't need to remove it at least you can fix it. So if you want to fix it at product page i will assign it to you.

But i will need a proper fix making functioning animation in product page as well as other pages animation has to be working the way they are already.

Thank You.
