### ISSUE TITLE
[Bug]: Social media icons are static even when scrolled down

### ISSUE THREAD

**Issue by KavyaBS123** [ChromeGaming/Community-Page#37]
### Give a brief about the bug ✍️

Description :
The social media icons are static even when scrolled down they must stay at the upper position itself. This might improve the UI of the website.

### What is the expected behavior? 🤔

Description
Description :
The social media icons are static even when scrolled down they must stay at the upper position itself. This might improve the UI of the website.

### Provide step by step information reproduce the bug 📄

Description
this can improved by **Fixed Positioning:** Add the position: fixed; property to the element containing the social media icons. You can also define properties like left: 0; (to position it on the left) and top: 50%; (to position it vertically in the center).

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by KavyaBS123** [comment]
Thank you!!

**Comment by reshamsai150** [comment]
adding hovering effect to icons to make the website more interactive assign this issue to me @Durgesh4993
