### ISSUE TITLE
[Feature Request]: Integrating Docker into the project

### ISSUE THREAD

**Issue by Ratangulati** [ChromeGaming/Community-Page#379]
### 🎮 feature Request

feature logic and basic descriptionDocker is a must for open-source projects nowadays as it has its benefits.

Use Case
Dockerfile has many benefits but consistency and isolation stand out the most.

I will also be updating the docs for it.

### Point down the features

Docker allows you to package your entire application, including its dependencies, into a single container. That makes sure your application will run across different environments.
another benefit is that it runs in its environment without interfering with other applications or the host system.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment]
hi @Ratangulati,
also do Create a updation in learn.md as well as readme file regarding the same. explaining each step of process.

Thank You

**Comment by agarwalhimanshugaya** [comment]
@Manaregr8 if no one do this issue kindly assign this issue to me i will resolve this
