### ISSUE TITLE
[Feature]:  Search Feature 

### ISSUE THREAD

**Issue by sivaprasath2004** [ChromeGaming/Community-Page#40]
### 🎮 feature Request

If the header search box empty we can any other search doesn't response.
- I will expected to the search box can be enter the `text` that can displayed `Result ` and shortlist.

### Point down the features

This is can be more efficient for the users.

## Issue

[Screencast from 2024-05-12 08-23-12.webm](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121082414/7bc4cb3d-8bb5-44b7-98d1-c233f803db0f)

## Expected
[Screencast from 2024-05-12 08-10-53.webm](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121082414/efcadc0b-8489-40f7-b35b-94ed18c7b182)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.
