### ISSUE TITLE
[Bug]: Navbar links are misaligned

### ISSUE THREAD

**Issue by Ridhima10** [ChromeGaming/Community-Page#417]
### Give a brief about the bug ✍️

![image](https://github.com/user-attachments/assets/d11def9d-0b74-4551-9c25-cadc85b0e73f)

### What is the expected behavior? 🤔

Needs to be aligned perfectly

### Provide step by step information to reproduce the bug 📄

N/A

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by vivi2004** [comment]
Hey I  want's to contribute in  the  " Navbar links are misaligned "  would you please assign me the work so that  I can  work on it
