### ISSUE TITLE
[New Feature]: Navigation bar more responsive and creative

### ISSUE THREAD

**Issue by hritika2409** [ChromeGaming/Community-Page#42]
### 🎮 feature Request

feature logic and basic description

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by hritika2409** [comment]
I can work on this .Please assign me to do so as i have  experience regrading the same.I have already addressed this issue on my website

https://github.com/GameSphere-MultiPlayer/Community-Page/assets/117531823/a66e8200-d3b2-4f1b-8015-adf12a8c163c

**Comment by Akshatakapare** [comment]
I would like to contribute to this issue. Could you please assign this issue to me?

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.

**Comment by nilesh5566** [comment]
I would like to contribute to this issue. Could you please assign me this issue under GSSoc'24.

**Comment by Rishitatripathi** [comment]
Please assign me this issue under GSSoc'24.
