### ISSUE TITLE
[Bug]: Contact us doens't have label 

### ISSUE THREAD

**Issue by dhruv8433** [ChromeGaming/Community-Page#422]
### Give a brief about the bug ✍️

Description

@ChromeGaming

check this out, 

### What is the expected behavior? 🤔

Description

Contact us have propr label so user can understand which feild is used for which input

### Provide step by step information to reproduce the bug 📄

Description

![image](https://github.com/user-attachments/assets/6617d1c0-d887-49da-a60f-a0a0fa337045)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by dhruv8433** [comment]
hey @Manaregr8 

this contact us form reside on this url : "https://github.com/ChromeGaming/Chrome-Gaming-Certification/blob/main/certificate-generator/src/Compenents/Contact.jsx"

so is it ok to make pr on this repo : https://github.com/ChromeGaming/Chrome-Gaming-Certification ?

**Comment by Ridhima10** [comment]
@Manaregr8  i can fix this right away. Kindly assign me this issue
