### ISSUE TITLE
[New Feature]: Converting the leaderboard from long html to js using concept of mapping 

### ISSUE THREAD

**Issue by Jagpreet153** [ChromeGaming/Community-Page#44]
### 🎮 feature Request

feature logic and basic description
I can write the code using mapping concept of js to maintain the readability of code 

### Point down the features

feature points
It would look similar to this

![Screenshot 2024-05-12 111602](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/119691733/25e4e87c-1e55-4ec2-84ba-68fa2b9230fc)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Jagpreet153 Could you please explain more what you want to do, If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Jagpreet153** [comment]
@Durgesh4993 The code of leaderboard is made using raw HTML which makes it very long and reduces readability of code . I would be writing the code by converting the leaderboard details in JSON format and by fetching the details of the objects in js file . It  reduces length of code and makes easy for a user to understand the working of your file. It also reduces time to load your file .

**Comment by Vyomrana02** [comment]
@Durgesh4993 if anyone is not working on this issue can you assign it to me.

**Comment by Durgesh4993** [comment]
Can you explain more

**Comment by Durgesh4993** [comment]
Could you do one thing, through API we can get the top contributors, from our GitHub repository

**Comment by Vyomrana02** [comment]
@Jagpreet153  wants to add kind of dynamic data. ie saving the data in JSON format and in the main code use .map() method so if next time want to add more data then can do at ease.

**Comment by Vyomrana02** [comment]
@Durgesh4993  yes I can do it.
You want to add top contributor list in read.me file. 
Can i create an new issue for it.?

**Comment by Durgesh4993** [comment]
Could you do one thing, through API we can get the top contributors, from our GitHub repository

**Comment by Durgesh4993** [comment]
No In leaderboard, not in readme file

**Comment by Vyomrana02** [comment]
Yes, I am Creating an new issue for this.

**Comment by Jagpreet153** [comment]
Thank you @Vyomrana02 for explaining the issue @Durgesh4993 Now could you please assign this issue to me
