### ISSUE TITLE
[Bug]: CSS File not linked properly

### ISSUE THREAD

**Issue by Vaibhav-Kumar-K-R** [ChromeGaming/Community-Page#443]
### Give a brief about the bug ✍️

Description
When you navigate to http://localhost:3000/products page
the design, font and the colors are not applied properly linked to the html file.
![image](https://github.com/user-attachments/assets/51c71db6-4267-40d8-8b88-9678ea7d5af2)

### What is the expected behavior? 🤔

Description
Please assign this issue to me.

### Provide step by step information to reproduce the bug 📄

Description
Set up the project as given and navigate to http://localhost:3000/products

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Apeksha-22** [comment]
please assign it to me.

**Comment by Ishika1323** [comment]
please assign to me

**Comment by somasekhar774** [comment]
I am interested in doing this task please assign it to me
