### ISSUE TITLE
[New Feature]:  Change logo of the website

### ISSUE THREAD

**Issue by Ridhima10** [ChromeGaming/Community-Page#53]
### 🎮 feature Request

i would like to change the logo of the website since it is very simple

### Point down the features

![Screenshot 2024-05-12 200145](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/85826117/baf4935b-a269-467c-92ec-2401acac0117)
The font in this image is very attractive which make your website appealing. I would like to change the logo with this font

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Ridhima10 Connect with me on discord, i want to see your designs

**Comment by Ridhima10** [comment]
@Durgesh4993  I have messaged you on discord in group as well as personally. please check

**Comment by Ridhima10** [comment]
![Screenshot 2024-05-15 162419](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/85826117/6d0e84aa-0c30-4a72-9e28-5651d861f0de)

i have made this logo which matches your theme
if you like this i will make minor changes like size adjustment and push it
i can also change this as per your demand 

@Manaregr8 Kindly review this

**Comment by Manaregr8** [comment]
> ![Screenshot 2024-05-15 162419](https://private-user-images.githubusercontent.com/85826117/331872640-6d0e84aa-0c30-4a72-9e28-5651d861f0de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjk3NTcsIm5iZiI6MTcxNjEyOTQ1NywicGF0aCI6Ii84NTgyNjExNy8zMzE4NzI2NDAtNmQwZTg0YWEtMGMzMC00YTcyLTllMjgtNTY1MWQ4NjFmMGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDE0MzczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZjlkZGNiMWNmZWRjNDgwNzdjMTQwNGZiOGEzMDlhMGI2OWVhYmU1NjA1NmNlNzRiZWM1MDgyMWUyOTk1ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ejJeyTDUwELigVjBQOZRaEvikTrVF5ujrboCUStqzMw)
> 
> i have made this logo which matches your theme if you like this i will make minor changes like size adjustment and push it i can also change this as per your demand
> 
> @Manaregr8 Kindly review this

Hi @Ridhima10 ,

The logo looks nice, but I would prefer if the text in the center of the logo matches the typography used in the GIF. This way, there won't be a noticeable difference like there is now.

Thank you!
![dsdsdsdsdsdsdsdsdsdsdsdsdsds](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/99804338/6d3a49f6-cf2e-4a2d-888e-9009693c7277)

**Comment by Ridhima10** [comment]
@Manaregr8 I can change it to the desired font as well

**Comment by Manaregr8** [comment]
> @Manaregr8 I can change it to the desired font as well

@Ridhima10 Go for it.

**Comment by Ridhima10** [comment]
You haven't assigned me this issue yet
