### ISSUE TITLE
[New Feature]: Logo of the website should be on appear with the name of the website in the header

### ISSUE THREAD

**Issue by Coder-Kartikey** [ChromeGaming/Community-Page#56]
### 🎮 feature Request

I will set the logo of the website aside the name of the website in the header .
![Screenshot 2024-05-12 214621](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/158288146/4909486d-dffa-45f6-b59f-b4e18b9c4f6b)

### Point down the features

I will also make this responsive so that it will give best user experience in all the devices.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.

**Comment by Coder-Kartikey** [comment]
I have generated a pr request so please review it and tell if any changes are required or if it is ok then please approve it.
