### ISSUE TITLE
[Bug]: Alignment of the upload button 

### ISSUE THREAD

**Issue by Ankur-Rai-19** [ChromeGaming/Community-Page#68]
### Give a brief about the bug ✍️

Alignment of the upload button required changes so that it looks good 

![Capture1](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/125396300/35d7ce29-17e8-41af-a67b-cadd30451b28)

### What is the expected behavior? 🤔

The upload button should be in the center of the above image

![Capture2](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/125396300/1b0d10cc-d3b6-4244-acf7-5faf16fbd4fd)

### Provide step by step information reproduce the bug 📄

Need some changes in the CSS section so that it can come to the center

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
