### ISSUE TITLE
[New Feature]: Adding hover effect on the elemnts in the navbar

### ISSUE THREAD

**Issue by souvik-maity** [ChromeGaming/Community-Page#74]
### 🎮 feature Request

A hovering effect over the elements on the navbar can improve the ui.
![Screenshot 2024-05-14 041528](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/145227417/3634187d-9ce3-47c1-a45b-adcd10dfeee0)

### Point down the features

it should change into a different color text with a underline so that it creates a clickable effect.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@souvik-maity Please raise any other issue, because someone is already working on it...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and I would love to contribute, can you please assign me this issue.
