### ISSUE TITLE
[Bug]: Alignment of the Table need to be changed

### ISSUE THREAD

**Issue by Ankur-Rai-19** [ChromeGaming/Community-Page#94]
## The alignment of the Progress column in the table is not proper starting from the 4th serial number. It requires changes.

![P 1](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/125396300/52e31694-6e50-41d9-b50c-ca3c7595b69d)

## The alignment should look like this as given below image

![S 1](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/125396300/23e8cdf8-94bf-4d30-9d2f-40a9a94c314a)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayushrskiaa** [comment]
@Durgesh4993  I can do it. please assign it me.
