### ISSUE TITLE
[New Feature]: Add Animation to Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by thevijayshankersharma** [ChromeGaming/Community-Page#98]
### 🎮 feature Request

The current dark/light mode toggle lacks animation, resulting in a sudden change in appearance that can be jarring for users.

### Point down the features

Implement animation effects to smoothly transition between dark and light modes when toggling. This could involve a fade effect, sliding animation, or similar transition to enhance the user experience

I am an open-source contributor and would like to contribute this feature enhancement to the project.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@thevijayshankersharma Please change image color also
